### ISSUE TITLE
Defining which perl to use

### ISSUE THREAD

**Issue by biobenkj** [spundhir/PARE#3]
Several of the scripts in PARE have a #!/usr/bin/perl -w at the top which can lead to a problem with defining which perl version/installation to use if multiple versions are installed.

Changing it to #!/usr/bin/env perl will allow the user to define which perl installation they would like to use based on whatever comes first in PATH.

Happy to set up a pull request.

**Comment by spundhir** [comment]
Thanks man. I agree with your observation, and have accordingly edited the #! header. Please feel free to set up a pull request to incorporate further improvements, if any.
