### ISSUE TITLE
parallel: command not found

### ISSUE THREAD

**Issue by gangxuehzau** [spundhir/PARE#4]
Hi there,
I got something wrong when I use your PARE. It's ok when I use the test data that you provided for us,but there is a error when I use my data :

> " Determine common NFR between replicates ~/software/spundhir-PARE-0e89a50/bin/nfrAnaAll: line 402: parallel: command not found"
> ~/software/spundhir-PARE-0e89a50/bin/nfrAnaAll: line 387: parallel: command not found

This is my code `pare -i ENCFF001KOY.bam,ENCFF001KPA.bam -o results -m mm9 -p 10 &> pare.log`
and I have tried change my data's name to ` pare -i h3k4me1_Rep1.bam,h3k4me1_Rep2.bam -o results -m mm9 -p 10 &> pare.log`
Thanks for your help.

Gang

**Comment by spundhir** [comment]
Hi Gang,

Thanks for using PARE. It seems like your machine is missing parallel software. If you are using ubuntu, it can be installed using "(sudo) apt-get install parallel".. On OSx it can installed using homebrew "(sudo) brew install parallel".. More details are here https://www.gnu.org/software/parallel/

PARE uses parallel to do the computations simultaneously for multiple chromosomes (makes it faster). However, if you remove -p 10 option from your command... PARE not longer needs parallel but would obviosusly take longer to finish.

pare -i ENCFF001KOY.bam,ENCFF001KPA.bam -o results -m mm9 &> pare.log

Hope this helps.. and please let me know if some other issue comes up.

Regards,

sachin

**Comment by gangxuehzau** [comment]
Thank you sachin,It works.
Gang
