### ISSUE TITLE
Whether PARE is useful for H3K27ac data

### ISSUE THREAD

**Issue by tianwen0003** [spundhir/PARE#5]
Hi :
I  want to find the valley of H3k27ac signals as enhancer region , whether this software is helpful?

**Comment by spundhir** [comment]
Hi,

Yes, you can certainly do that. Please note that this will only give you a list of active enhancers, as compare to when we use H3K4me1 where we also predict poised enhancers.

**Comment by tianwen0003** [comment]
Thanks for your reply, I have tried this method for H3k27ac data, but got some new problems.
Firstly, I got some warning message as shown below, but this did not seem to affect the application of PARE, am I right?
> /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied
> /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied
>  /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied
> /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied
> /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: 
> /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied
> /home/TW/biosoft/PARE-master/bin/checkPrerequisite: line 44: /home/TW/biosoft/PARE-master/share/R/checkRModule.R: Permission denied

Secondly，when PARA started to predict nucleosome free regions for each replicate, I got some warning message as shown below, I am not sure whether this will affect the result.
> [main_samview] region "chr1:249218229-119526" could not be parsed. Continue anyway.
> [main_samview] region "chr10:135208761-189854" could not be parsed. Continue anyway.
> [main_samview] region "chr11:134479088-73892" could not be parsed. Continue anyway.
> [main_samview] region "chr12:133758520-20207039" could not be parsed. Continue anyway.
> [main_samview] region "chr13:115085600-19409901" could not be parsed. Continue anyway.
> [main_samview] region "chr14:107281795-20398590" could not be parsed. Continue anyway.
> [main_samview] region "chr15:102285888-89103" could not be parsed. Continue anyway.
> [main_samview] region "chr16:90173362-13445" could not be parsed. Continue anyway.
> [main_samview] region "chr17:81151787-90069" could not be parsed. Continue anyway.
> [main_samview] region "chr18:78005386-267057" could not be parsed. Continue anyway.
> [main_samview] region "chr19:59093045-33363" could not be parsed. Continue anyway.
> [main_samview] region "chr2:243062476-218340" could not be parsed. Continue anyway.
> [main_samview] region "chr20:62888408-9825412" could not be parsed. Continue anyway.
> [main_samview] region "chr21:48057401-16279080" could not be parsed. Continue anyway.
> [main_samview] region "chr22:51195920-104038" could not be parsed. Continue anyway.
> [main_samview] region "chr3:197877618-28034" could not be parsed. Continue anyway.
> [main_samview] region "chr4:191044195-91528" could not be parsed. Continue anyway.
> [main_samview] region "chr5:180691796-235420" could not be parsed. Continue anyway.
> [main_samview] region "chr6:170894795-30482" could not be parsed. Continue anyway.
> [main_samview] region "chr7:159112186-182154" could not be parsed. Continue anyway.
> [main_samview] region "chr8:146283673-178247" could not be parsed. Continue anyway.
> [main_samview] region "chr9:141045560--1" could not be parsed. Continue anyway.
> [main_samview] region "chrX:154843011-2709334" could not be parsed. Continue anyway.

Finally, after adjusting the p-value to FDR, I only got two significant  valley region, whether this is due to I only have one replicate for input ?

**Comment by spundhir** [comment]
Thanks for your message. For clarity, I addess each of the issues point wise below:

1. Permission denied. The R script is not executable. Please try following on your command line "chmod 755 /home/TW/biosoft/PARE-master/share/R/*.R"

2. This should not happen. Is this error in "blockbuster_threshold_nfr.log" or "nfrAna_random.log" files? Secondly, please check if you are provide the right genome assembly information (-m).

3. Too few regions could be because of low ChIP coverage? Could be an idea to try reducing the -l parameter value.
